### ISSUE TITLE
急

### ISSUE THREAD

**Issue by chungchao1** [Goku404/flappy-bird-GEC6818-#1]
博主加QQ2955742336有问题想问你

**Comment by Goku404** [comment]
您好我有时间会在 github 上回复ヽ(°▽°)ノ



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月14日(周二) 上午8:27
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Goku404/flappy-bird-GEC6818-] 急 (#1)




 
博主加QQ2955742336有问题想问你
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chungchao1** [comment]
博主你这个项目，我们可以直接在我们板子上运行吗

**Comment by chungchao1** [comment]
博主你这个项目，我们可以直接在我们板子上运行吗

**Comment by Goku404** [comment]
亲，在我的板子上可以，src文件夹源码我写死了文件路径&nbsp;&nbsp;
建议看懂源码喔 _(:* ｣∠)_



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月14日(周二) 上午8:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Goku404/flappy-bird-GEC6818-] 急 (#1)




 
博主你这个项目，我们可以直接在我们板子上运行吗
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chungchao1** [comment]
博主可以给个联系方式吗

**Comment by chungchao1** [comment]
因为我现在比较急，请您指导指导我

**Comment by Goku404** [comment]
诶，因为我不是很有时间，如果您是实训找项目的话，下源码自己领悟吧
顺便帮我star 一下&nbsp; &nbsp;3Q ＞_＜

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月14日(周二) 上午9:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Goku404/flappy-bird-GEC6818-] 急 (#1)




 
因为我现在比较急，请您指导指导我
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chungchao1** [comment]
明天要汇报用，所以很急，只需要在我板子上运行出来就行了，大佬救命

**Comment by Goku404** [comment]
爱莫能助啊，大兄弟
我还要上课呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月14日(周二) 上午9:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Goku404/flappy-bird-GEC6818-] 急 (#1)




 
明天要汇报用，所以很急，只需要在我板子上运行出来就行了，大佬救命
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chungchao1** [comment]
那您什么时候有时间？？？

**Comment by Goku404** [comment]
QQ: 2387167651&nbsp; &nbsp;我不一定能帮到你，这个我也是发着玩而已

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月14日(周二) 上午10:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Goku404/flappy-bird-GEC6818-] 急 (#1)




 
那您什么时候有时间？？？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
